<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Liste des Maisons</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 80%;
            max-width: 800px;
            margin: 20px;
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        li {
            background-color: #f9f9f9;
            margin-bottom: 10px;
            padding: 10px;
            border-radius: 4px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        li:nth-child(odd) {
            background-color: #e9e9e9;
        }
        button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Maisons</h1>
        <?php if (count($this->maisons) > 0) : ?>
            <ul>
                <?php foreach ($this->maisons as $maison) : ?>
                    <li>
                        <div>
                            <strong>Adresse :</strong> <?php echo $maison->RUE; ?>, <?php echo $maison->VILLE; ?>, <?php echo $maison->PAYS; ?>
                        </div>
                        <a href="<?php echo Util_Route::url("detail", "Maisons", ["id" => (string)$maison->NUM_MAISON]); ?>">
                            <button id="btn">Détail</button>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else : ?>
            <p>Aucune maison disponible.</p>
        <?php endif; ?>
    </div>
</body>
</html>